# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/coyove/go/src/github.com/coyove/simdgrep

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/coyove/go/src/github.com/coyove/simdgrep

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/coyove/go/src/github.com/coyove/simdgrep/CMakeFiles /home/coyove/go/src/github.com/coyove/simdgrep//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/coyove/go/src/github.com/coyove/simdgrep/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named simdgrep

# Build rule for target.
simdgrep: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simdgrep
.PHONY : simdgrep

# fast build rule for target.
simdgrep/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simdgrep.dir/build.make CMakeFiles/simdgrep.dir/build
.PHONY : simdgrep/fast

#=============================================================================
# Target rules for targets named pcre2-8-static

# Build rule for target.
pcre2-8-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pcre2-8-static
.PHONY : pcre2-8-static

# fast build rule for target.
pcre2-8-static/fast:
	$(MAKE) $(MAKESILENT) -f pcre2/CMakeFiles/pcre2-8-static.dir/build.make pcre2/CMakeFiles/pcre2-8-static.dir/build
.PHONY : pcre2-8-static/fast

#=============================================================================
# Target rules for targets named pcre2-posix-static

# Build rule for target.
pcre2-posix-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pcre2-posix-static
.PHONY : pcre2-posix-static

# fast build rule for target.
pcre2-posix-static/fast:
	$(MAKE) $(MAKESILENT) -f pcre2/CMakeFiles/pcre2-posix-static.dir/build.make pcre2/CMakeFiles/pcre2-posix-static.dir/build
.PHONY : pcre2-posix-static/fast

#=============================================================================
# Target rules for targets named pcre2grep

# Build rule for target.
pcre2grep: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pcre2grep
.PHONY : pcre2grep

# fast build rule for target.
pcre2grep/fast:
	$(MAKE) $(MAKESILENT) -f pcre2/CMakeFiles/pcre2grep.dir/build.make pcre2/CMakeFiles/pcre2grep.dir/build
.PHONY : pcre2grep/fast

grepper.o: grepper.c.o
.PHONY : grepper.o

# target to build an object file
grepper.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simdgrep.dir/build.make CMakeFiles/simdgrep.dir/grepper.c.o
.PHONY : grepper.c.o

grepper.i: grepper.c.i
.PHONY : grepper.i

# target to preprocess a source file
grepper.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simdgrep.dir/build.make CMakeFiles/simdgrep.dir/grepper.c.i
.PHONY : grepper.c.i

grepper.s: grepper.c.s
.PHONY : grepper.s

# target to generate assembly for a file
grepper.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simdgrep.dir/build.make CMakeFiles/simdgrep.dir/grepper.c.s
.PHONY : grepper.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simdgrep.dir/build.make CMakeFiles/simdgrep.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simdgrep.dir/build.make CMakeFiles/simdgrep.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simdgrep.dir/build.make CMakeFiles/simdgrep.dir/main.c.s
.PHONY : main.c.s

pathutil.o: pathutil.c.o
.PHONY : pathutil.o

# target to build an object file
pathutil.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simdgrep.dir/build.make CMakeFiles/simdgrep.dir/pathutil.c.o
.PHONY : pathutil.c.o

pathutil.i: pathutil.c.i
.PHONY : pathutil.i

# target to preprocess a source file
pathutil.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simdgrep.dir/build.make CMakeFiles/simdgrep.dir/pathutil.c.i
.PHONY : pathutil.c.i

pathutil.s: pathutil.c.s
.PHONY : pathutil.s

# target to generate assembly for a file
pathutil.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simdgrep.dir/build.make CMakeFiles/simdgrep.dir/pathutil.c.s
.PHONY : pathutil.c.s

pcre2/deps/sljit/sljit_src/sljitLir.o: pcre2/deps/sljit/sljit_src/sljitLir.c.o
.PHONY : pcre2/deps/sljit/sljit_src/sljitLir.o

# target to build an object file
pcre2/deps/sljit/sljit_src/sljitLir.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simdgrep.dir/build.make CMakeFiles/simdgrep.dir/pcre2/deps/sljit/sljit_src/sljitLir.c.o
.PHONY : pcre2/deps/sljit/sljit_src/sljitLir.c.o

pcre2/deps/sljit/sljit_src/sljitLir.i: pcre2/deps/sljit/sljit_src/sljitLir.c.i
.PHONY : pcre2/deps/sljit/sljit_src/sljitLir.i

# target to preprocess a source file
pcre2/deps/sljit/sljit_src/sljitLir.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simdgrep.dir/build.make CMakeFiles/simdgrep.dir/pcre2/deps/sljit/sljit_src/sljitLir.c.i
.PHONY : pcre2/deps/sljit/sljit_src/sljitLir.c.i

pcre2/deps/sljit/sljit_src/sljitLir.s: pcre2/deps/sljit/sljit_src/sljitLir.c.s
.PHONY : pcre2/deps/sljit/sljit_src/sljitLir.s

# target to generate assembly for a file
pcre2/deps/sljit/sljit_src/sljitLir.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simdgrep.dir/build.make CMakeFiles/simdgrep.dir/pcre2/deps/sljit/sljit_src/sljitLir.c.s
.PHONY : pcre2/deps/sljit/sljit_src/sljitLir.c.s

printer.o: printer.c.o
.PHONY : printer.o

# target to build an object file
printer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simdgrep.dir/build.make CMakeFiles/simdgrep.dir/printer.c.o
.PHONY : printer.c.o

printer.i: printer.c.i
.PHONY : printer.i

# target to preprocess a source file
printer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simdgrep.dir/build.make CMakeFiles/simdgrep.dir/printer.c.i
.PHONY : printer.c.i

printer.s: printer.c.s
.PHONY : printer.s

# target to generate assembly for a file
printer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simdgrep.dir/build.make CMakeFiles/simdgrep.dir/printer.c.s
.PHONY : printer.c.s

stack.o: stack.c.o
.PHONY : stack.o

# target to build an object file
stack.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simdgrep.dir/build.make CMakeFiles/simdgrep.dir/stack.c.o
.PHONY : stack.c.o

stack.i: stack.c.i
.PHONY : stack.i

# target to preprocess a source file
stack.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simdgrep.dir/build.make CMakeFiles/simdgrep.dir/stack.c.i
.PHONY : stack.c.i

stack.s: stack.c.s
.PHONY : stack.s

# target to generate assembly for a file
stack.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simdgrep.dir/build.make CMakeFiles/simdgrep.dir/stack.c.s
.PHONY : stack.c.s

vendor.o: vendor.c.o
.PHONY : vendor.o

# target to build an object file
vendor.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simdgrep.dir/build.make CMakeFiles/simdgrep.dir/vendor.c.o
.PHONY : vendor.c.o

vendor.i: vendor.c.i
.PHONY : vendor.i

# target to preprocess a source file
vendor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simdgrep.dir/build.make CMakeFiles/simdgrep.dir/vendor.c.i
.PHONY : vendor.c.i

vendor.s: vendor.c.s
.PHONY : vendor.s

# target to generate assembly for a file
vendor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simdgrep.dir/build.make CMakeFiles/simdgrep.dir/vendor.c.s
.PHONY : vendor.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... pcre2-8-static"
	@echo "... pcre2-posix-static"
	@echo "... pcre2grep"
	@echo "... simdgrep"
	@echo "... grepper.o"
	@echo "... grepper.i"
	@echo "... grepper.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... pathutil.o"
	@echo "... pathutil.i"
	@echo "... pathutil.s"
	@echo "... pcre2/deps/sljit/sljit_src/sljitLir.o"
	@echo "... pcre2/deps/sljit/sljit_src/sljitLir.i"
	@echo "... pcre2/deps/sljit/sljit_src/sljitLir.s"
	@echo "... printer.o"
	@echo "... printer.i"
	@echo "... printer.s"
	@echo "... stack.o"
	@echo "... stack.i"
	@echo "... stack.s"
	@echo "... vendor.o"
	@echo "... vendor.i"
	@echo "... vendor.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

